package org.example.transactionsapi.domain.service;

import org.example.transactionsapi.domain.model.Transaction;
import org.example.transactionsapi.domain.model.TransactionNotFoundException;
import org.example.transactionsapi.domain.port.out.TransactionRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class TransactionServiceTest {

    @Mock
    private TransactionRepository repository;

    private TransactionService service;

    @BeforeEach
    void setUp() {
        service = new TransactionService(repository);
    }

    // --- createTransaction (POST — auto-generated id) ---

    @Test
    void shouldReturnAutoGeneratedId() {
        Long id = service.createTransaction(250.0, "payment", null);
        assertThat(id).isNotNull().isPositive();
    }

    @Test
    void shouldGenerateMonotonicallyIncreasingIds() {
        Long first  = service.createTransaction(100.0, "food", null);
        Long second = service.createTransaction(200.0, "food", null);
        assertThat(second).isGreaterThan(first);
    }

    @Test
    void shouldPersistTransactionWithAutoGeneratedId() {
        Long id = service.createTransaction(250.0, "payment", 99L);

        ArgumentCaptor<Transaction> captor = ArgumentCaptor.forClass(Transaction.class);
        verify(repository).save(captor.capture());

        Transaction saved = captor.getValue();
        assertThat(saved.id()).isEqualTo(id);
        assertThat(saved.amount()).isEqualTo(250.0);
        assertThat(saved.type()).isEqualTo("payment");
        assertThat(saved.parentId()).isEqualTo(99L);
    }

    // --- upsertTransaction (PUT — caller-supplied id) ---

    @Test
    void shouldPersistTransactionWithExplicitId() {
        service.upsertTransaction(42L, 100.0, "cars", null);

        ArgumentCaptor<Transaction> captor = ArgumentCaptor.forClass(Transaction.class);
        verify(repository).save(captor.capture());

        assertThat(captor.getValue().id()).isEqualTo(42L);
        assertThat(captor.getValue().parentId()).isNull();
    }

    // --- getTransactionById ---

    @Test
    void shouldReturnTransactionWhenFound() {
        Transaction tx = new Transaction(1L, 100.0, "payment", null);
        when(repository.findById(1L)).thenReturn(Optional.of(tx));

        assertThat(service.getTransactionById(1L)).isEqualTo(tx);
    }

    @Test
    void shouldThrowWhenTransactionNotFoundById() {
        when(repository.findById(42L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.getTransactionById(42L))
                .isInstanceOf(TransactionNotFoundException.class)
                .hasMessageContaining("42");
    }

    // --- getTransactionIdsByType ---

    @Test
    void shouldReturnIdsForMatchingType() {
        when(repository.findByType("cars")).thenReturn(List.of(
                new Transaction(1L, 500.0, "cars", null),
                new Transaction(2L, 300.0, "cars", null)
        ));

        List<Long> ids = service.getTransactionIdsByType("cars");

        assertThat(ids).containsExactlyInAnyOrder(1L, 2L);
    }

    @Test
    void shouldReturnEmptyListWhenNoTransactionsMatchType() {
        when(repository.findByType("unknown")).thenReturn(List.of());

        assertThat(service.getTransactionIdsByType("unknown")).isEmpty();
    }

    // --- getTransactionSum ---

    @Test
    void shouldReturnAmountAloneWhenNoChildren() {
        Transaction tx = new Transaction(1L, 500.0, "cars", null);
        when(repository.findById(1L)).thenReturn(Optional.of(tx));
        when(repository.findByParentId(1L)).thenReturn(List.of());

        assertThat(service.getTransactionSum(1L)).isEqualTo(500.0);
    }

    @Test
    void shouldSumTransitivelyAcrossThreeLevels() {
        // 10 (5000) <- 11 (10000) <- 12 (5000)
        Transaction t10 = new Transaction(10L, 5000.0, "cars", null);
        Transaction t11 = new Transaction(11L, 10000.0, "shopping", 10L);
        Transaction t12 = new Transaction(12L, 5000.0, "shopping", 11L);

        when(repository.findById(10L)).thenReturn(Optional.of(t10));
        when(repository.findByParentId(10L)).thenReturn(List.of(t11));
        when(repository.findByParentId(11L)).thenReturn(List.of(t12));
        when(repository.findByParentId(12L)).thenReturn(List.of());

        assertThat(service.getTransactionSum(10L)).isEqualTo(20000.0);
    }

    @Test
    void shouldSumFromChildNodeIgnoringAncestors() {
        Transaction t11 = new Transaction(11L, 10000.0, "shopping", 10L);
        Transaction t12 = new Transaction(12L, 5000.0, "shopping", 11L);

        when(repository.findById(11L)).thenReturn(Optional.of(t11));
        when(repository.findByParentId(11L)).thenReturn(List.of(t12));
        when(repository.findByParentId(12L)).thenReturn(List.of());

        assertThat(service.getTransactionSum(11L)).isEqualTo(15000.0);
    }

    @Test
    void shouldThrowTransactionNotFoundExceptionForUnknownId() {
        when(repository.findById(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.getTransactionSum(999L))
                .isInstanceOf(TransactionNotFoundException.class)
                .hasMessageContaining("999");
    }
}
