package org.example.transactionsapi.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Inbound DTO for POST /transactions requests.
 * The transaction id is auto-generated by the service; only the business fields are supplied.
 */
public record CreateTransactionRequest(
        double amount,
        String type,
        @JsonProperty("parent_id") Long parentId
) {}
